[package]
name = "ac-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "ac"
path = "src/main.rs"

[dependencies]
ac-net.workspace = true
ac-groups.workspace = true
ac-files.workspace = true
ac-peers.workspace = true
fs4 = "1"
libp2p-stream = "0.4.0-alpha"
futures = "0.3"
serde.workspace = true
ciborium.workspace = true
hex.workspace = true
libp2p.workspace = true
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
thiserror.workspace = true
rusqlite.workspace = true

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
