[package]
name = "ac-files"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ac-net.workspace = true
ac-groups.workspace = true
serde.workspace = true
rusqlite.workspace = true
sha2.workspace = true
hex.workspace = true
thiserror.workspace = true
tracing.workspace = true


[dev-dependencies]
tempfile = "3"
ciborium.workspace = true

[lints]
workspace = true
