use std::fmt::Write as _;
use std::path::Path;
use std::process::exit;

fn main() {
    let manifest = match std::env::var("CARGO_MANIFEST_DIR") {
        Ok(dir) => dir,
        Err(e) => fail(&format!("CARGO_MANIFEST_DIR: {e}")),
    };
    let dir = Path::new(&manifest).join("src").join("sources");
    println!("cargo:rerun-if-changed={}", dir.display());

    let entries = match std::fs::read_dir(&dir) {
        Ok(entries) => entries,
        Err(e) => fail(&format!("could not read {}: {e}", dir.display())),
    };

    let mut names = Vec::new();
    for entry in entries {
        let path = match entry {
            Ok(entry) => entry.path(),
            Err(e) => fail(&format!("could not read {}: {e}", dir.display())),
        };
        if path.extension().is_none_or(|ext| ext != "rs") {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        match path.file_stem().and_then(|stem| stem.to_str()) {
            Some(stem) => names.push(stem.to_owned()),
            None => fail(&format!("{} has no usable name", path.display())),
        }
    }
    names.sort();

    if names.is_empty() {
        fail("src/sources is empty: this build could import from nothing");
    }

    let mut out = String::from("// Generated by build.rs from src/sources. Do not edit.\n");
    for name in &names {
        let file = dir.join(format!("{name}.rs")).display().to_string();
        let _ = write!(out, "\n#[path = {file:?}]\nmod {name};\n");
    }

    let _ = writeln!(out, "\nstatic KNOWN: &[(&str, SourceType)] = &[");
    for name in &names {
        let _ = writeln!(out, "    ({name}::NAME, {name}::TYPE),");
    }
    let _ = writeln!(out, "];");

    let _ = writeln!(
        out,
        "\nfn opener(name: &str) -> Option<Opener> {{\n    match name {{"
    );
    for name in &names {
        let _ = writeln!(out, "        {name}::NAME => Some({name}::open),");
    }
    let _ = writeln!(out, "        _ => None,\n    }}\n}}");

    let generated = match std::env::var("OUT_DIR") {
        Ok(dir) => Path::new(&dir).join("registry.rs"),
        Err(e) => fail(&format!("OUT_DIR: {e}")),
    };
    if let Err(e) = std::fs::write(&generated, out) {
        fail(&format!("could not write {}: {e}", generated.display()));
    }
}

fn fail(why: &str) -> ! {
    eprintln!("ac-import: {why}");
    exit(1);
}
