[package]
name = "ac-import"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rusqlite.workspace = true
thiserror.workspace = true
sha2.workspace = true
md-5.workspace = true
sha1.workspace = true
hex.workspace = true

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
